-- MySQL Script generated by MySQL Workbench
-- Wed Jun 19 09:32:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbVacinacao
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `dbVacinacao` DEFAULT CHARACTER SET utf8 ;
USE `dbVacinacao` ;

-- -----------------------------------------------------
-- Table `dbVacinacao`.`vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbVacinacao`.`vacina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomeVacina` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nomeVacina_UNIQUE` (`nomeVacina` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbVacinacao`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbVacinacao`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NOT NULL,
  `logradouro` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(5) NOT NULL,
  `complemento` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbVacinacao`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbVacinacao`.`paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_endereco` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `cns` VARCHAR(15) NOT NULL,
  `celular` VARCHAR(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `nomeCuidador` VARCHAR(100) NULL,
  `telefoneCuidador` VARCHAR(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_paciente_endereco1_idx` (`id_endereco` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `cns_UNIQUE` (`cns` ASC) VISIBLE,
  UNIQUE INDEX `celular_UNIQUE` (`celular` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_endereco1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `dbVacinacao`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbVacinacao`.`agenteSaude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbVacinacao`.`agenteSaude` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `celular` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE,
  UNIQUE INDEX `celular_UNIQUE` (`celular` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbVacinacao`.`agendamentoVisita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbVacinacao`.`agendamentoVisita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataVisita` DATETIME NOT NULL,
  `situacao` VARCHAR(20) NOT NULL,
  `id_agenteSaude` INT NOT NULL,
  `id_paciente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agendamentoVisita_agenteSaude1_idx` (`id_agenteSaude` ASC) VISIBLE,
  INDEX `fk_agendamentoVisita_paciente1_idx` (`id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_agendamentoVisita_agenteSaude1`
    FOREIGN KEY (`id_agenteSaude`)
    REFERENCES `dbVacinacao`.`agenteSaude` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamentoVisita_paciente1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `dbVacinacao`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbVacinacao`.`prontuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbVacinacao`.`prontuario` (
  `id_vacina` INT NOT NULL,
  `id_agendamentoVisita` INT NOT NULL,
  INDEX `fk_vacina_has_agendamentoVisita_agendamentoVisita1_idx` (`id_agendamentoVisita` ASC) VISIBLE,
  INDEX `fk_vacina_has_agendamentoVisita_vacina_idx` (`id_vacina` ASC) VISIBLE,
  CONSTRAINT `fk_vacina_has_agendamentoVisita_vacina`
    FOREIGN KEY (`id_vacina`)
    REFERENCES `dbVacinacao`.`vacina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vacina_has_agendamentoVisita_agendamentoVisita1`
    FOREIGN KEY (`id_agendamentoVisita`)
    REFERENCES `dbVacinacao`.`agendamentoVisita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
