-- MySQL Script generated by MySQL Workbench
-- Tue Jun 18 22:16:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE `mydb`;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
-- Remove or define columns for this table if needed

-- -----------------------------------------------------
-- Table `mydb`.`vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vacina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomeVacina` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NOT NULL,
  `logradouro` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(5) NOT NULL,
  `complemento` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_endereco` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `cns` VARCHAR(15) NOT NULL,
  `celular` VARCHAR(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `nomeCuidador` VARCHAR(100) NULL,
  `telefoneCuidador` VARCHAR(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_paciente_endereco1_idx` (`id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_endereco1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `mydb`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`agenteSaude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agenteSaude` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `celular` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`agendamentoVisita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agendamentoVisita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataVisita` DATETIME NOT NULL,
  `situacao` VARCHAR(20) NOT NULL,
  `agenteSaude_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agendamentoVisita_agenteSaude1_idx` (`agenteSaude_id` ASC) VISIBLE,
  CONSTRAINT `fk_agendamentoVisita_agenteSaude1`
    FOREIGN KEY (`agenteSaude_id`)
    REFERENCES `mydb`.`agenteSaude` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`prontuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prontuario` (
  `id_vacina` INT NOT NULL,
  `id_agendamentoVisita` INT NOT NULL,
  PRIMARY KEY (`id_vacina`, `id_agendamentoVisita`),
  INDEX `fk_vacina_has_agendamentoVisita_agendamentoVisita1_idx` (`id_agendamentoVisita` ASC) VISIBLE,
  INDEX `fk_vacina_has_agendamentoVisita_vacina_idx` (`id_vacina` ASC) VISIBLE,
  CONSTRAINT `fk_vacina_has_agendamentoVisita_vacina`
    FOREIGN KEY (`id_vacina`)
    REFERENCES `mydb`.`vacina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vacina_has_agendamentoVisita_agendamentoVisita1`
    FOREIGN KEY (`id_agendamentoVisita`)
    REFERENCES `mydb`.`agendamentoVisita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historico` (
  `agendamentoVisita_id` INT NOT NULL,
  `agendamentoVisita_agenteSaude_id` INT NOT NULL,
  `id_paciente` INT NOT NULL,
  `id_paciente_endereco` INT NOT NULL,
  PRIMARY KEY (`agendamentoVisita_id`, `agendamentoVisita_agenteSaude_id`, `id_paciente`, `id_paciente_endereco`),
  INDEX `fk_agendamentoVisita_has_paciente_paciente1_idx` (`id_paciente` ASC, `id_paciente_endereco` ASC) VISIBLE,
  INDEX `fk_agendamentoVisita_has_paciente_agendamentoVisita1_idx` (`agendamentoVisita_id` ASC, `agendamentoVisita_agenteSaude_id` ASC) VISIBLE,
  CONSTRAINT `fk_agendamentoVisita_has_paciente_agendamentoVisita1`
    FOREIGN KEY (`agendamentoVisita_id`, `agendamentoVisita_agenteSaude_id`)
    REFERENCES `mydb`.`agendamentoVisita` (`id`, `agenteSaude_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamentoVisita_has_paciente_paciente1`
    FOREIGN KEY (`id_paciente`, `id_paciente_endereco`)
    REFERENCES `mydb`.`paciente` (`id`, `id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
